### ISSUE TITLE
improve doc: README.md

### ISSUE THREAD

**Issue by mw66** [huntlabs/hunt-grpc#14]
I was following README.md

```
$ git clone https://github.com/huntlabs/grpc-dlang
$ cd grpc-dlang

# then I was following README.md
$ dub build :protoc-gen-d
Sub package "grpc:protoc-gen-d" doesn't exist.
```

Finally, I figured out, what it really means is:
```
$ git clone https://github.com/dcarp/protobuf-d
$ cd protobuf-d

# then following README.md
$ dub build :protoc-gen-d
...
```

And later in the doc:

from the section "Generating protobuf code"

it should updated with the latest directory change, and just be:
```
$ cd examples/SimpleDemo/proto/
$ ./generate.sh
$ cd ..
$ ./build.sh 
```

**Comment by Heromyth** [comment]
Thanks. Fixed in commit https://github.com/huntlabs/grpc-dlang/commit/3d19059e4ace4f72293a08affe189ba0978876e9.
