### ISSUE TITLE
streaming and bidirectional streaming grpc?

### ISSUE THREAD

**Issue by timotheecour** [huntlabs/hunt-grpc#3]
is that supported? if not is there a timeline?

**Comment by zoujiaqing** [comment]
This will be supported later.

**Comment by zhangyuchun** [comment]
this support gprc.

**Comment by timotheecour** [comment]
@zhangyuchun that's great, are there any examples ? ideally something in https://github.com/huntlabs/hunt-grpc/tree/master/example (right now I don't see any Stream example)

**Comment by zhangyuchun** [comment]
@timotheecour sorry.  i mean that none streaming mode support grpc's none streaming mode right now . stream mode will be support later.

**Comment by zhangyuchun** [comment]
now support bidirectional
