### ISSUE TITLE
Client part not working on Windows 10.

### ISSUE THREAD

**Issue by aldocd4** [huntlabs/hunt-grpc#7]
After successfully building the client and the server, it seems the client part is not working very well.

I have this error after the ConnectEx call in IOCP.d (I displayed this line with tracef before the first return in checkErro(): 

```
erro=-1, dwLastError=10022
```

The server part is working, I tried it accessing the ip and port with browser, I can see logs.

Do you know why ? thanks

**Comment by Heromyth** [comment]
Fixed in Hunt: https://github.com/huntlabs/hunt/commit/ba238f79e43cdbfc7ebe8e908dda22283f1f944f
